{
'name':'kts_account',
'version':'1.0',
'author':'Prashant',
'depends':['account','sale','purchase','base','account_accountant','stock'],
'data':['kts_account_extension_view.xml',
        'security/ir.model.access.csv',],
'website':'http://www.kreativtech.com',
'installable':True,
'application':True,
}
